title: "cat README.md"
description: "My personal notebook for coding, learning, and technical exploration. Sharing what I discover so you can learn too."
author:
  name: "Bhuwan Pandit"
  email: "bhuwanpandit110@gmail.com"
  url: "https://bhuwanpandit.me/blogs"
github_username: "bp7968h"

remote_theme: pages-themes/hacker@v0.2.0

google_analytics: "G-MPRDNFKEBP"

baseurl: "/"
permalink: /:title
paginate: 3
paginate_path: /page/:num/

sass:
  sass_dir: _scss

future: true
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
