base_url = "https://bhuwanpandit.me"

title = "Bhuwan Pandit"
description = "Full stack developer uncovering abstractions to understand the tech underneath and deliver secure, innovative software solutions."
author = "Bhuwan Pandit"
default_language = "en"
generate_feeds = true
feed_filenames = ["rss.xml"]
taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]

compile_sass = false

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
math = false
mermaid = false
comment = true
social_image = "icons/github.svg"

[extra.profile]
name = "Bhuwan Pandit"
username = "bp7968h"
bio = "Full stack developer uncovering abstractions to understand the tech underneath."
avatar_url = "https://avatars.githubusercontent.com/u/126598388"
avatar_invert = false
skills = ["html5", "css3", "tailwindcss", "javascript", "react", "nodedotjs", "express", "java", "springboot","rust","actix", "python", "flask", "mysql", "postgresql", "mongodb", "docker", "nginx", "linux", "git", "github" ,"githubactions", "gitlab"]
social = [
    { name = "github", url = "https://github.com/bp7968h" },
    { name = "linkedin", url = "https://www.linkedin.com/in/bhuwan-pandit-889807193/" },
    { name = "rss", url = "$BASE_URL/rss.xml" },
    { name = "cv", url = "https://drive.google.com/file/d/1v5_CHJ8Dix1Q169y9NndFz7_bveO0NOg/view?usp=sharing" }
]
journey = [
    { date = "April 2024 - Present", title = "Chichester District Council", address = "United Kindom, Chichester", sub_title = "ICT Development Officer", description = "Building dynamic e-forms and automated processes using HTML, CSS, and JavaScript, ensuring GDPR compliance. Managing CMS, documenting systems, supporting web services, and enhancing accessibility (WCAG 2.1) while optimizing workflows.", part = "Work", image_url = "icons/bug.svg" },
    { date = "May 2023 - May 2024",title = "University of Greenwich", address = "United Kindom, Greenwich", sub_title = "Junior Software Developer", description = "Conducted research for the EUNOMIA project, deploying the instance from scratch. Led Yak software development using Mongodb, Expressjs, React and Node.js. Designed tests, implemented CI/CD pipelines, and authored documentation.", part = "Work", image_url = "icons/email.svg" }
]

[[extra.menu]]
name = "Home"
url = "$BASE_URL"

[[extra.menu]]
name = "Projects"
url = "$BASE_URL/projects"

[[extra.menu]]
name = "Blogs"
url = "$BASE_URL/blogs"

[[extra.menu]]
name = "Archives"
url = "$BASE_URL/archives"

[extra.footer]
since = 2024
license = "bp7968h"
license_url = "https://bhuwanpandit.me"

[extra.giscus]
repo = "bp7968h/bp7968h.github.io"
repo_id = "R_kgDOLTnpRw"
category = "Post Comments"
category_id = "DIC_kwDOLTnpR84CjwXr"
mapping = "pathname"
strict = 1
reactions_enabled = 1
emit_metadata = 0
input_position = "top"
theme = "dark"
lang = "en"
loading = "lazy"
