base_url = "https://bhuwanpandit.me"

title = "Bhuwan Pandit"
description = "Full stack developer uncovering abstractions to understand the tech underneath and deliver secure, innovative software solutions."
author = "Bhuwan Pandit"
default_language = "en"
generate_feeds = true
feed_filenames = ["rss.xml"]
taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]

compile_sass = false

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
math = false
mermaid = false
comment = true
social_image = "icons/github.svg"

[extra.profile]
name = "Bhuwan Pandit"
username = "bp7968h"
bio = "Full stack developer uncovering abstractions to understand the tech underneath."
avatar_url = "https://avatars.githubusercontent.com/u/126598388"
avatar_invert = false
skills = ["html5", "css3", "tailwindcss", "javascript", "react", "nodedotjs", "express", "java", "springboot","rust","actix", "python", "flask", "mysql", "postgresql", "mongodb", "docker", "nginx", "linux", "git", "github" ,"githubactions", "gitlab"]

[[extra.profile.social]]
name = "github"
url = "https://github.com/bp7968h"

[[extra.profile.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/bhuwan-pandit-889807193/"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/rss.xml"

[[extra.profile.social]]
name = "Resume"
logo = "readdotcv"
url = "https://drive.google.com/file/d/1v5_CHJ8Dix1Q169y9NndFz7_bveO0NOg/view?usp=sharing"

[[extra.menu]]
name = "Home"
url = "$BASE_URL"

[[extra.menu]]
name = "Projects"
url = "$BASE_URL/projects"

[[extra.menu]]
name = "Blogs"
url = "$BASE_URL/blogs"

[[extra.menu]]
name = "Archives"
url = "$BASE_URL/archives"

[extra.footer]
since = 2024
license = "bp7968h"
license_url = "https://bhuwanpandit.me"

[extra.giscus]
repo = "bp7968h/bp7968h.github.io"
repo_id = "R_kgDOLTnpRw"
category = "Post Comments"
category_id = "DIC_kwDOLTnpR84CjwXr"
mapping = "pathname"
strict = 1
reactions_enabled = 1
emit_metadata = 0
input_position = "top"
theme = "dark"
lang = "en"
loading = "lazy"
